
export const fazendas = [
    {
      id: 1,
      nome: "Fazenda 1",
      municipio: "Município 1 - UF",
      area: "100.00 ha",
      consultores: [
        {
          tipo: "Consultor Técnico",
          nome: "João da Silva",
        },
        {
          tipo: "Consultor Vendas",
          nome: "Maria da Silva",
        },
      ],
    },
    {
      id: 2,
      nome: "Fazenda 2",
      municipio: "Município 2 - UF",
      area: "200.00 ha",
      consultores: [

        {
            tipo: "Consultor Técnico",
            nome: "Gabriel Godinho Ferreira",
            dados: "Dados do Carlos",
            contato: "Contato do Carlos",
          },
        {
          tipo: "Consultor Vendas",
          nome: "Ana da Silva",
          dados: "Dados da Ana",
          contato: "Contato da Ana",
        },
      ],
    },
  ];
  
  export const visitas = [
    {
      id: 1,
      consultor: "José da Silva",
      data: "01/07/2024",
      tipo: "Prospecção",
      idFazenda: 1,
      link: "https://exemplo.com/visita/1",
    },
    {
      id: 2,
      consultor: "Maria Pereira",
      data: "03/07/2024",
      tipo: "Manutenção",
      idFazenda: 1,
      link: "https://exemplo.com/visita/2",
    },
    {
      id: 3,
      consultor: "Carlos Fernandes",
      data: "05/07/2024",
      tipo: "Consulta Técnica",
      idFazenda: 1,
      link: "https://exemplo.com/visita/3",
    },
    {
      id: 4,
      consultor: "Ana Silva",
      data: "07/07/2024",
      tipo: "Auditoria",
      idFazenda: 1,
      link: "https://exemplo.com/visita/4",
    },
    {
      id: 5,
      consultor: "João Carvalho",
      data: "09/07/2024",
      tipo: "Visita de Campo",
      idFazenda: 1,
      link: "https://exemplo.com/visita/5",
    },
    {
      id: 6,
      consultor: "Lucas Almeida",
      data: "11/07/2024",
      tipo: "Monitoramento",
      idFazenda: 1,
      link: "https://exemplo.com/visita/6",
    },
    {
      id: 7,
      consultor: "Fernanda Gomes",
      data: "13/07/2024",
      tipo: "Prospecção",
      idFazenda: 1,
      link: "https://exemplo.com/visita/7",
    },
    {
      id: 8,
      consultor: "Ricardo Oliveira",
      data: "15/07/2024",
      tipo: "Manutenção",
      idFazenda: 1,
      link: "https://exemplo.com/visita/8",
    },
    {
      id: 9,
      consultor: "Patrícia Souza",
      data: "17/07/2024",
      tipo: "Consulta Técnica",
      idFazenda: 1,
      link: "https://exemplo.com/visita/9",
    },
    {
      id: 10,
      consultor: "Thiago Santos",
      data: "19/07/2024",
      tipo: "Auditoria",
      idFazenda: 1,
      link: "https://exemplo.com/visita/10",
    },
    {
      id: 11,
      consultor: "Gabriel Silva",
      data: "21/07/2024",
      tipo: "Visita de Campo",
      idFazenda: 1,
      link: "https://exemplo.com/visita/11",
    },
    {
      id: 12,
      consultor: "Luana Costa",
      data: "23/07/2024",
      tipo: "Monitoramento",
      idFazenda: 2,
      link: "https://exemplo.com/visita/12",
    },
    {
      id: 13,
      consultor: "Pedro Fernandes",
      data: "25/07/2024",
      tipo: "Prospecção",
      idFazenda: 2,
      link: "https://exemplo.com/visita/13",
    },
    {
      id: 14,
      consultor: "Mariana Alves",
      data: "27/07/2024",
      tipo: "Manutenção",
      idFazenda: 2,
      link: "https://exemplo.com/visita/14",
    },
    {
      id: 15,
      consultor: "Rafael Moreira",
      data: "29/07/2024",
      tipo: "Consulta Técnica",
      idFazenda: 2,
      link: "https://exemplo.com/visita/15",
    },
    {
      id: 16,
      consultor: "Juliana Lima",
      data: "31/07/2024",
      tipo: "Auditoria",
      idFazenda: 2,
      link: "https://exemplo.com/visita/16",
    },
    {
      id: 17,
      consultor: "Vinícius Cardoso",
      data: "02/08/2024",
      tipo: "Visita de Campo",
      idFazenda: 2,
      link: "https://exemplo.com/visita/17",
    },
    {
      id: 18,
      consultor: "Beatriz Silva",
      data: "04/08/2024",
      tipo: "Monitoramento",
      idFazenda: 2,
      link: "https://exemplo.com/visita/18",
    },
    {
      id: 19,
      consultor: "Rodrigo Castro",
      data: "06/08/2024",
      tipo: "Prospecção",
      idFazenda: 2,
      link: "https://exemplo.com/visita/19",
    },
    {
      id: 20,
      consultor: "Carla Mendes",
      data: "08/08/2024",
      tipo: "Manutenção",
      idFazenda: 2,
      link: "https://exemplo.com/visita/20",
    },
  ];
  